### ISSUE TITLE
Syntax error with version 0.6.1

### ISSUE THREAD

**Issue by clauded** [ckan/ckanext-xloader#118]
I'm getting the following error message on some datasets : **xloader error: syntax error at or near ")"**

```
2020-09-16 22:23:13,222 INFO  [dd0bba8e-420d-4308-b4b0-b3607b402ae2] Downloaded ok - 72.5 KB
File hash: fcc17f5da1c107d4112218fa1f988cc8
2020-09-16 22:23:13,225 INFO  [dd0bba8e-420d-4308-b4b0-b3607b402ae2] File hash: fcc17f5da1c107d4112218fa1f988cc8
Loading CSV
2020-09-16 22:23:13,227 INFO  [dd0bba8e-420d-4308-b4b0-b3607b402ae2] Loading CSV
'Just load with messytables' mode is: False
2020-09-16 22:23:13,230 INFO  [dd0bba8e-420d-4308-b4b0-b3607b402ae2] 'Just load with messytables' mode is: False
Ensuring character coding is UTF8
2020-09-16 22:23:13,248 INFO  [dd0bba8e-420d-4308-b4b0-b3607b402ae2] Ensuring character coding is UTF8
Deleting "4e1f089a-8a04-40ea-bc10-abeb33aac042" from DataStore.
2020-09-16 22:23:13,332 INFO  [dd0bba8e-420d-4308-b4b0-b3607b402ae2] Deleting "4e1f089a-8a04-40ea-bc10-abeb33aac042" from DataStore.
2020-09-16 22:23:13,342 DEBUG [ckanext.datastore.logic.action] Setting datastore_active=False on resource 4e1f089a-8a04-40ea-bc10-abeb33aac042
Fields: []
2020-09-16 22:23:13,450 INFO  [dd0bba8e-420d-4308-b4b0-b3607b402ae2] Fields: []
2020-09-16 22:23:13,471 DEBUG [ckanext.datastore.logic.action] Setting datastore_active=True on resource 4e1f089a-8a04-40ea-bc10-abeb33aac042
Copying to database...
2020-09-16 22:23:13,554 INFO  [dd0bba8e-420d-4308-b4b0-b3607b402ae2] Copying to database...
2020-09-16 22:23:13,568 ERROR [ckanext.xloader.jobs] xloader error: syntax error at or near ")"
LINE 1: COPY "4e1f089a-8a04-40ea-bc10-abeb33aac042" () FROM STDIN WI...
                                                     ^
, Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckanext-xloader/ckanext/xloader/jobs.py", line 75, in xloader_data_into_datastore
    xloader_data_into_datastore_(input, job_dict)
  File "/usr/lib/ckan/default/src/ckanext-xloader/ckanext/xloader/jobs.py", line 212, in xloader_data_into_datastore_
    direct_load()
  File "/usr/lib/ckan/default/src/ckanext-xloader/ckanext/xloader/jobs.py", line 173, in direct_load
    logger=logger)
  File "/usr/lib/ckan/default/src/ckanext-xloader/ckanext/xloader/loader.py", line 219, in load_csv
    f)
SyntaxError: syntax error at or near ")"
LINE 1: COPY "4e1f089a-8a04-40ea-bc10-abeb33aac042" () FROM STDIN WI...

```

**Comment by maxclac** [comment]
No news about this?

**Comment by ThrawnCA** [comment]
The error appears to indicate that no headers were identified in the file. Are you able to attach it here?
