### ISSUE TITLE
JobError: Connection timed out after 30s

### ISSUE THREAD

**Issue by clauded** [ckan/ckanext-xloader#119]
I'm getting connection time outs on some site. Would it be possible to define a new ckan.ini variable so the connection time can be increased?

```
URL time out after 30s
2020-09-25 14:53:43,710 WARNI [fd147473-1c82-4ad8-9f36-6b1706466f99] URL time out after 30s
2020-09-25 14:53:43,741 ERROR [ckanext.xloader.jobs] xloader error: Connection timed out after 30s, Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckanext-xloader/ckanext/xloader/jobs.py", line 73, in xloader_data_into_datastore
    xloader_data_into_datastore_(input, job_dict)
  File "/usr/lib/ckan/default/src/ckanext-xloader/ckanext/xloader/jobs.py", line 223, in xloader_data_into_datastore_
    DOWNLOAD_TIMEOUT))
JobError: Connection timed out after 30s
```

**Comment by Ukarus** [comment]
This might be really late, but in case someone experience a similar problem in the future this workaround could be useful.

I was experiencing a similar problem in which I was not able to upload resources to datastore because xloader was getting connection timeout errors when trying to download the resource to upload it to postgres. The production server in which Ckan was operating was behind a private network that was not allowing the server to ping to his own hostname, so a solution I found was to edit the /etc/hosts file and map the hostname to localhost in this way:

`
127.0.0.1 myhost.com
`

I hope this turns out to be useful to someone who experiences a similar issue

**Comment by dsanchezmatilla** [comment]
Hi! I'm getting the same timeout error when trying to load resources that are not stored in CKAN's internal storage (i.e., external URLs).

Is there any ongoing fix or fork in progress to solve this? Maybe some workaround or configuration for CKAN environments?

``` bash
xloader  | URL time out after 30s
xloader  | 2025-06-18 14:22:48,716 WARNI [116bc6e2-293f-46ec-9be0-e1b15fd79ddb] URL time out after 30s
xloader  | 2025-06-18 14:22:48,729 ERROR [ckanext.xloader.jobs] xloader error: Connection timed out after 30s, Traceback (most recent call last):
xloader  | Traceback (most recent call last):
xloader  |   File "/usr/local/lib/python3.10/site-packages/ckanext/xloader/jobs.py", line 106, in xloader_data_into_datastore
xloader  |     xloader_data_into_datastore_(input, job_dict, logger)
xloader  |   File "/usr/local/lib/python3.10/site-packages/ckanext/xloader/jobs.py", line 192, in xloader_data_into_datastore_
xloader  |     tmp_file, file_hash = _download_resource_data(resource, data, api_key,
xloader  |   File "/usr/local/lib/python3.10/site-packages/ckanext/xloader/jobs.py", line 383, in _download_resource_data
xloader  |     raise JobError('Connection timed out after {}s'.format(
xloader  | ckanext.xloader.job_exceptions.JobError: Connection timed out after 30s```
