### ISSUE TITLE
SSL issue by an upload with xloader

### ISSUE THREAD

**Issue by maxclac** [ckan/ckanext-xloader#149]
Hi!

I am using CKAN 2.9.3 with ckanext-xloader.0.8.0. I have a productive CKAN instance with https.
I set ckanext.xloader.ssl_verify to False but I still get an SSLError when I try to upload a csv file:

```
Traceback (most recent call last):
  File "/usr/lib/ckan/datapusher/lib/python3.8/site-packages/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 336, in push_to_datastore
    resource = get_resource(resource_id, ckan_url, api_key)
  File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 282, in get_resource
    r = requests.post(url,
  File "/usr/lib/ckan/datapusher/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/ckan/datapusher/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/ckan/datapusher/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/ckan/datapusher/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/ckan/datapusher/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='myckan.com', port=443): Max retries exceeded with url: /api/3/action/resource_show (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
```
 
What could be wrong here?

Best regards

**Comment by maxclac** [comment]
It is working when I directly go to `/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py` and I set `SSL_VERIFY = False`, which means that the config file is ignored.
