### ISSUE TITLE
Unterminated string literal

### ISSUE THREAD

**Issue by yaythecloud** [ckan/ckanext-xloader#199]
I am probably missing something, but I am attempting to follow the installation instructions to run this on the same server as my CKAN instance and I am getting an error when I run a status for SyntaxError: unterminated string literal (detected at line 1). This is coming from command.py on line 127.

**Comment by ThrawnCA** [comment]
I can't reproduce this in our own environment. Can you check that your copy of the XLoader is unchanged with `git status`?

**Comment by yaythecloud** [comment]
Sorry been a while and just getting back around to working on this. here is what I am seeing locally.

77e657b0b014:/srv/app# ckan -c ckan.ini xloader status
2024-03-04 15:40:09,559 INFO  [ckan.cli] Using configuration file /srv/app/ckan.ini
2024-03-04 15:40:09,560 INFO  [ckan.config.environment] Loading static files from public
2024-03-04 15:40:09,975 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
2024-03-04 15:40:11,062 WARNI [ckanext.reclineview.plugin] The Recline-based views are deprecated andwill be removed in future versions
2024-03-04 15:40:11,119 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
2024-03-04 15:40:11,410 WARNI [ckan.config.middleware.flask_app] Extensions are excluded from CSRF protection! We allow extensions to run without CSRF protection but it will be forced future releases. Read the documentation for more information on how to add CSRF protection to your extension.
Traceback (most recent call last):
  File "/usr/bin/ckan", line 8, in <module>
    sys.exit(ckan())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/ckanext/xloader/cli.py", line 22, in status
    cmd.print_status()
  File "/usr/lib/python3.10/site-packages/ckanext/xloader/command.py", line 130, in print_status
    job_params = eval(job.description.replace(
  File "<string>", line 1
    ({'api_key': '01129a66-b492-4d49-b2ab-b6332c85b175', 'job_type': 'xloader_to...)
