### ISSUE TITLE
Error in xloader

### ISSUE THREAD

**Issue by riccardoricciagid** [ckan/ckanext-xloader#222]
Hi to all.
I have installed CKAN 2.10 and all works very well...  The job submit to the xloader works fine but the status reply with an error:
```
2024-07-27 18:33:15,483 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 8, in <module>
    sys.exit(ckan())
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckanext/xloader/cli.py", line 22, in status
    cmd.print_status()
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckanext/xloader/command.py", line 130, in print_status
    job_params = eval(job.description.replace(
  File "<string>", line 1
    ({'api_key': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJBSTU3TjVlVzNkO...)
                 ^
SyntaxError: unterminated string literal (detected at line 1)

```
What about this?

**Comment by ThrawnCA** [comment]
What version of XLoader are you using?

**Comment by duttonw** [comment]
based on your error code, did you include an extra ' in your api key config?

are you doing a developer install or a pipy install?
https://github.com/ckan/ckanext-xloader?tab=readme-ov-file#developer-installation

**Comment by duttonw** [comment]
did you resovle your issue

**Comment by riccardoricciagid** [comment]
With the 2.11 version and a different kind of data I have no errors.
