### ISSUE TITLE
Xloader API token problem

### ISSUE THREAD

**Issue by zozol31** [ckan/ckanext-xloader#227]
I have an error with my xloader config

```
 valadmin@ckan:/etc/ckan/default/ckanext-xloader/ckanext/xloader$ ckan -c /etc/ckan/default/ckan.ini xloader status
2024-10-01 12:01:56,401 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2024-10-01 12:01:56,401 INFO  [ckan.config.environment] Loading static files from public
2024-10-01 12:01:56,709 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2024-10-01 12:01:57,217 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2024-10-01 12:01:57,533 WARNI [ckan.config.middleware.flask_app] Extensions are excluded from CSRF protection! We allow extensions to run without CSRF protection but it will be forced future releases. Read the documentation for more information on how to add CSRF protection to your extension.
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 8, in <module>
    sys.exit(ckan())
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/etc/ckan/default/ckanext-xloader/ckanext/xloader/cli.py", line 22, in status
    cmd.print_status()
  File "/etc/ckan/default/ckanext-xloader/ckanext/xloader/command.py", line 140, in print_status
    job_params = eval(job.description.replace(
  File "<string>", line 1
    ({'api_key': "'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI0Sm5xamtDZGg4...)
                 ^
SyntaxError: unterminated string literal (detected at line 1)
**
```

From what i can see i have an issue with my api token (it's not the same as the one that i put in ckan.ini with
`ckanext.xloader.api_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJBX1N0TzNRN25wTDQ0NlpRWUNIek5XR3VKbWdqLVN3eUlYUDdQcUw4cVVFIiwiaWF0IjoxNzI3NzgyNzc2fQ.9rzZiRzqQReI6sX161UlzLYAWFNvHkmyV93coG9tzmY`

how can i put the good token api and why the one in the xloader status is not tge same ?

Thank you for your time.

**Comment by ThrawnCA** [comment]
What XLoader version are you running?

**Comment by zozol31** [comment]
I'm runing 1.0.1. I used to had the 0.12.2 but i had the same error with it .

**Comment by duttonw** [comment]
Please use the git install method, pypi is very out of date.  

please try with pip via git. ie

``pip install git+https://github.com/ckan/ckanext-xloader@(version tag or branch)``

``pip install git+https://github.com/ckan/ckanext-xloader@master``

**Comment by duttonw** [comment]
Hi @zozol31 ,

For latest versions of ckan, you need to generate an admin api key since they have moved away from 'anon' admin python scripts.

You can set this config key in your ckan.ini.

``ckanext.xloader.api_token = ##PRIVATE-KEY-HERE##`` 
https://github.com/qld-gov-au/opswx-ckan-cookbook/blob/master/templates/default/ckan_properties.ini.erb#L311

i.e.
ckan config-tool ckan.ini "ckan.xloader.api_token=$(ckan user token add ckan_admin xloader| tail -n 1 | tr -d '\t')"
https://github.com/qld-gov-au/ckan/blob/30704f3fa713b7e07de3185e48ff92b392556019/.devcontainer/setup.sh#L22

**Comment by zozol31** [comment]
I already did what you said I have master release installed and ckanext.xloader.api_token = ##PRIVATE-KEY-HERE## is set on ckan.ini

**Comment by zozol31** [comment]
I've just seen that the wrong api was in config_declaration.yaml what can i do for xloader to go fetch the right api_token ?

**Comment by ThrawnCA** [comment]
We're not encountering the same issue on data.qld.gov.au; we put the token in `ckanext.xloader.api_token` and it works fine.
