### ISSUE TITLE
Failure when running with numpy >= 1.16

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckanext-xloader#79]
We're experimenting with XLoader, and the initial results are very promising, but it fails when running with the default (latest) numpy version, 1.16.5. Looks like https://github.com/numpy/numpy/issues/14012

    mod_wsgi (pid=18160): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
    Traceback (most recent call last):
      File "/etc/ckan/default/apache.wsgi", line 11, in <module>
        application = loadapp('config:%s' % config_filepath)
      File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
        return loadobj(APP, uri, name=name, **kw)
      File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
        return context.create()
      File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
        return self.object_type.invoke(self)
      File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
        return fix_call(context.object, context.global_conf, **context.local_conf)
      File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
        val = callable(*args, **kw)
      File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 55, in make_app
        load_environment(conf, app_conf)
      File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 116, in load_environment
        p.load_all()
      File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 140, in load_all
        load(*plugins)
      File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 154, in load
        service = _get_service(plugin)
      File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 256, in _get_service
        return plugin.load()(name=plugin_name)
      File "/usr/lib/ckan/default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
        return self.resolve()
      File "/usr/lib/ckan/default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/lib/ckan/default/src/ckanext-xloader/ckanext/xloader/plugin.py", line 6, in <module>
        from ckanext.xloader import action, auth
      File "/usr/lib/ckan/default/src/ckanext-xloader/ckanext/xloader/action.py", line 16, in <module>
        import jobs
      File "/usr/lib/ckan/default/src/ckanext-xloader/ckanext/xloader/jobs.py", line 23, in <module>
        import loader
      File "/usr/lib/ckan/default/src/ckanext-xloader/ckanext/xloader/loader.py", line 9, in <module>
        import messytables
      File "/usr/lib/ckan/default/lib/python2.7/site-packages/messytables/__init__.py", line 22, in <module>
        from messytables.pdf import PDFTableSet, PDFRowSet
      File "/usr/lib/ckan/default/lib/python2.7/site-packages/messytables/pdf.py", line 6, in <module>
        from pdftables import get_tables
      File "/usr/lib/ckan/default/lib/python2.7/site-packages/pdftables/__init__.py", line 1, in <module>
        from pdftables import *
      File "/usr/lib/ckan/default/lib/python2.7/site-packages/pdftables/pdftables.py", line 36, in <module>
        import numpy # TODO: remove this dependency
      File "/usr/lib/ckan/default/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
        from . import core
      File "/usr/lib/ckan/default/lib/python2.7/site-packages/numpy/core/__init__.py", line 40, in <module>
        from . import multiarray
      File "/usr/lib/ckan/default/lib/python2.7/site-packages/numpy/core/multiarray.py", line 13, in <module>
        from . import overrides
      File "/usr/lib/ckan/default/lib/python2.7/site-packages/numpy/core/overrides.py", line 46, in <module>
        """)
    RuntimeError: implement_array_function method already has a docstring

Perhaps the `requirements.txt` should explicitly set `numpy==1.15.4` to work around this? I can confirm that manually installing 1.15.4 fixed the problem for us.

**Comment by davidread** [comment]
I'm not clear what the problem is exactly, but I think we can avoid it by getting rid of pdftables: https://github.com/okfn/messytables/pull/186
I'll remove it from xloader's requirements.txt

**Comment by ThrawnCA** [comment]
That does seem to have resolved the numpy issue. Still encountering a different one, but I'll raise a separate issue for that.
